/// Auto-generated file - DO NOT EDIT MANUALLY
/// Generated by ForceFunctionReferences.py
/// Force references to function registration functions to ensure linking
/// This prevents the linker from excluding object files containing REGISTER_FUNCTION

namespace DB
{
    class FunctionFactory;
}

/// Functions defined in global namespace (upstream bugs)
extern void registerFunctionIsValidASCII(::DB::FunctionFactory & factory);

namespace DB
{

    /// Forward declarations of function registration functions
    /// These functions have external linkage and can be referenced
    extern void registerFunctionAESDecryptMysql(FunctionFactory & factory);
    extern void registerFunctionAESEncryptMysql(FunctionFactory & factory);
    extern void registerFunctionAbs(FunctionFactory & factory);
    extern void registerFunctionAcos(FunctionFactory & factory);
    extern void registerFunctionAcosh(FunctionFactory & factory);
    extern void registerFunctionActionName(FunctionFactory & factory);
    extern void registerFunctionAddDays(FunctionFactory & factory);
    extern void registerFunctionAddHours(FunctionFactory & factory);
    extern void registerFunctionAddInterval(FunctionFactory & factory);
    extern void registerFunctionAddMicroseconds(FunctionFactory & factory);
    extern void registerFunctionAddMilliseconds(FunctionFactory & factory);
    extern void registerFunctionAddMinutes(FunctionFactory & factory);
    extern void registerFunctionAddMonths(FunctionFactory & factory);
    extern void registerFunctionAddNanoseconds(FunctionFactory & factory);
    extern void registerFunctionAddQuarters(FunctionFactory & factory);
    extern void registerFunctionAddSeconds(FunctionFactory & factory);
    extern void registerFunctionAddWeeks(FunctionFactory & factory);
    extern void registerFunctionAddYears(FunctionFactory & factory);
    extern void registerFunctionAge(FunctionFactory & factory);
    extern void registerFunctionAppendTrailingCharIfAbsent(FunctionFactory & factory);
    extern void registerFunctionArea(FunctionFactory & factory);
    extern void registerFunctionArray(FunctionFactory & factory);
    extern void registerFunctionArrayAUC(FunctionFactory & factory);
    extern void registerFunctionArrayAggregation(FunctionFactory & factory);
    extern void registerFunctionArrayAll(FunctionFactory & factory);
    extern void registerFunctionArrayCompact(FunctionFactory & factory);
    extern void registerFunctionArrayConcat(FunctionFactory & factory);
    extern void registerFunctionArrayCount(FunctionFactory & factory);
    extern void registerFunctionArrayCumSum(FunctionFactory & factory);
    extern void registerFunctionArrayCumSumNonNegative(FunctionFactory & factory);
    extern void registerFunctionArrayDifference(FunctionFactory & factory);
    extern void registerFunctionArrayDistinct(FunctionFactory & factory);
    extern void registerFunctionArrayDotProduct(FunctionFactory & factory);
    extern void registerFunctionArrayElement(FunctionFactory & factory);
    extern void registerFunctionArrayEnumerate(FunctionFactory & factory);
    extern void registerFunctionArrayEnumerateDense(FunctionFactory & factory);
    extern void registerFunctionArrayEnumerateDenseRanked(FunctionFactory & factory);
    extern void registerFunctionArrayEnumerateUniq(FunctionFactory & factory);
    extern void registerFunctionArrayEnumerateUniqRanked(FunctionFactory & factory);
    extern void registerFunctionArrayExists(FunctionFactory & factory);
    extern void registerFunctionArrayFill(FunctionFactory & factory);
    extern void registerFunctionArrayFilter(FunctionFactory & factory);
    extern void registerFunctionArrayFirst(FunctionFactory & factory);
    extern void registerFunctionArrayFirstIndex(FunctionFactory & factory);
    extern void registerFunctionArrayFlatten(FunctionFactory & factory);
    extern void registerFunctionArrayFold(FunctionFactory & factory);
    extern void registerFunctionArrayIntersect(FunctionFactory & factory);
    extern void registerFunctionArrayJaccardIndex(FunctionFactory & factory);
    extern void registerFunctionArrayJoin(FunctionFactory & factory);
    extern void registerFunctionArrayLevenshtein(FunctionFactory & factory);
    extern void registerFunctionArrayMap(FunctionFactory & factory);
    extern void registerFunctionArrayPopBack(FunctionFactory & factory);
    extern void registerFunctionArrayPopFront(FunctionFactory & factory);
    extern void registerFunctionArrayPushBack(FunctionFactory & factory);
    extern void registerFunctionArrayPushFront(FunctionFactory & factory);
    extern void registerFunctionArrayRandomSample(FunctionFactory & factory);
    extern void registerFunctionArrayReduce(FunctionFactory & factory);
    extern void registerFunctionArrayReduceInRanges(FunctionFactory & factory);
    extern void registerFunctionArrayRemove(FunctionFactory & factory);
    extern void registerFunctionArrayResize(FunctionFactory & factory);
    extern void registerFunctionArrayReverse(FunctionFactory & factory);
    extern void registerFunctionArrayShiftOrRotate(FunctionFactory & factory);
    extern void registerFunctionArrayShingles(FunctionFactory & factory);
    extern void registerFunctionArrayShuffle(FunctionFactory & factory);
    extern void registerFunctionArraySlice(FunctionFactory & factory);
    extern void registerFunctionArraySort(FunctionFactory & factory);
    extern void registerFunctionArraySplit(FunctionFactory & factory);
    extern void registerFunctionArrayStringConcat(FunctionFactory & factory);
    extern void registerFunctionArrayUniq(FunctionFactory & factory);
    extern void registerFunctionArrayWithConstant(FunctionFactory & factory);
    extern void registerFunctionArrayZip(FunctionFactory & factory);
    extern void registerFunctionAscii(FunctionFactory & factory);
    extern void registerFunctionAsin(FunctionFactory & factory);
    extern void registerFunctionAsinh(FunctionFactory & factory);
    extern void registerFunctionAssumeNotNull(FunctionFactory & factory);
    extern void registerFunctionAtan(FunctionFactory & factory);
    extern void registerFunctionAtan2(FunctionFactory & factory);
    extern void registerFunctionAtanh(FunctionFactory & factory);
    extern void registerFunctionAuthenticatedUser(FunctionFactory & factory);
    extern void registerFunctionAvg2(FunctionFactory & factory);
    extern void registerFunctionBar(FunctionFactory & factory);
    extern void registerFunctionBase32Decode(FunctionFactory & factory);
    extern void registerFunctionBase32Encode(FunctionFactory & factory);
    extern void registerFunctionBase58Decode(FunctionFactory & factory);
    extern void registerFunctionBase58Encode(FunctionFactory & factory);
    extern void registerFunctionBasename(FunctionFactory & factory);
    extern void registerFunctionBinaryRepr(FunctionFactory & factory);
    extern void registerFunctionBitAnd(FunctionFactory & factory);
    extern void registerFunctionBitBoolMaskAnd(FunctionFactory & factory);
    extern void registerFunctionBitBoolMaskOr(FunctionFactory & factory);
    extern void registerFunctionBitCount(FunctionFactory & factory);
    extern void registerFunctionBitHammingDistance(FunctionFactory & factory);
    extern void registerFunctionBitNot(FunctionFactory & factory);
    extern void registerFunctionBitOr(FunctionFactory & factory);
    extern void registerFunctionBitRotateLeft(FunctionFactory & factory);
    extern void registerFunctionBitRotateRight(FunctionFactory & factory);
    extern void registerFunctionBitShiftLeft(FunctionFactory & factory);
    extern void registerFunctionBitShiftRight(FunctionFactory & factory);
    extern void registerFunctionBitSlice(FunctionFactory & factory);
    extern void registerFunctionBitSwapLastTwo(FunctionFactory & factory);
    extern void registerFunctionBitTest(FunctionFactory & factory);
    extern void registerFunctionBitTestAll(FunctionFactory & factory);
    extern void registerFunctionBitTestAny(FunctionFactory & factory);
    extern void registerFunctionBitToArray(FunctionFactory & factory);
    extern void registerFunctionBitWrapperFunc(FunctionFactory & factory);
    extern void registerFunctionBitXor(FunctionFactory & factory);
    extern void registerFunctionBitmap(FunctionFactory & factory);
    extern void registerFunctionBlockNumber(FunctionFactory & factory);
    extern void registerFunctionBlockSerializedSize(FunctionFactory & factory);
    extern void registerFunctionBlockSize(FunctionFactory & factory);
    extern void registerFunctionByteSize(FunctionFactory & factory);
    extern void registerFunctionByteSwap(FunctionFactory & factory);
    extern void registerFunctionCRC(FunctionFactory & factory);
    extern void registerFunctionCanonicalRand(FunctionFactory & factory);
    extern void registerFunctionCaseWithExpression(FunctionFactory & factory);
    extern void registerFunctionCastOrDefault(FunctionFactory & factory);
    extern void registerFunctionCastOverloadResolvers(FunctionFactory & factory);
    extern void registerFunctionCatBoostEvaluate(FunctionFactory & factory);
    extern void registerFunctionCbrt(FunctionFactory & factory);
    extern void registerFunctionChangeDate(FunctionFactory & factory);
    extern void registerFunctionChar(FunctionFactory & factory);
    extern void registerFunctionChdbVersion(FunctionFactory & factory);
    extern void registerFunctionClamp(FunctionFactory & factory);
    extern void registerFunctionCoalesce(FunctionFactory & factory);
    extern void registerFunctionCoding(FunctionFactory & factory);
    extern void registerFunctionCodingUUID(FunctionFactory & factory);
    extern void registerFunctionColorSRGBToOKLCH(FunctionFactory & factory);
    extern void registerFunctionCompareSubstrings(FunctionFactory & factory);
    extern void registerFunctionConcat(FunctionFactory & factory);
    extern void registerFunctionConcatWithSeparator(FunctionFactory & factory);
    extern void registerFunctionConnectionId(FunctionFactory & factory);
    extern void registerFunctionConv(FunctionFactory & factory);
    extern void registerFunctionConversion(FunctionFactory & factory);
    extern void registerFunctionCos(FunctionFactory & factory);
    extern void registerFunctionCosh(FunctionFactory & factory);
    extern void registerFunctionCountDigits(FunctionFactory & factory);
    extern void registerFunctionCountEqual(FunctionFactory & factory);
    extern void registerFunctionCountMatches(FunctionFactory & factory);
    extern void registerFunctionCountSubstrings(FunctionFactory & factory);
    extern void registerFunctionCountSubstringsCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionCountSubstringsCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionCurrentDatabase(FunctionFactory & factory);
    extern void registerFunctionCurrentQueryID(FunctionFactory & factory);
    extern void registerFunctionCurrentRoles(FunctionFactory & factory);
    extern void registerFunctionCurrentSchema(FunctionFactory & factory);
    extern void registerFunctionCurrentUser(FunctionFactory & factory);
    extern void registerFunctionCutFragment(FunctionFactory & factory);
    extern void registerFunctionCutQueryString(FunctionFactory & factory);
    extern void registerFunctionCutQueryStringAndFragment(FunctionFactory & factory);
    extern void registerFunctionCutToFirstSignificantSubdomain(FunctionFactory & factory);
    extern void registerFunctionCutToFirstSignificantSubdomainCustom(FunctionFactory & factory);
    extern void registerFunctionCutURLParameter(FunctionFactory & factory);
    extern void registerFunctionCutWWW(FunctionFactory & factory);
    extern void registerFunctionDateDiff(FunctionFactory & factory);
    extern void registerFunctionDateName(FunctionFactory & factory);
    extern void registerFunctionDateTimeToSnowflakeID(FunctionFactory & factory);
    extern void registerFunctionDateTrunc(FunctionFactory & factory);
    extern void registerFunctionDecodeHTMLComponent(FunctionFactory & factory);
    extern void registerFunctionDecodeXMLComponent(FunctionFactory & factory);
    extern void registerFunctionDecrypt(FunctionFactory & factory);
    extern void registerFunctionDefaultValueOfArgumentType(FunctionFactory & factory);
    extern void registerFunctionDefaultValueOfTypeName(FunctionFactory & factory);
    extern void registerFunctionDegrees(FunctionFactory & factory);
    extern void registerFunctionDemangle(FunctionFactory & factory);
    extern void registerFunctionDictGetKeys(FunctionFactory & factory);
    extern void registerFunctionDisplayName(FunctionFactory & factory);
    extern void registerFunctionDistribution(FunctionFactory & factory);
    extern void registerFunctionDivide(FunctionFactory & factory);
    extern void registerFunctionDivideDecimals(FunctionFactory & factory);
    extern void registerFunctionDivideOrNull(FunctionFactory & factory);
    extern void registerFunctionDomain(FunctionFactory & factory);
    extern void registerFunctionDomainWithoutWWW(FunctionFactory & factory);
    extern void registerFunctionDumpColumnStructure(FunctionFactory & factory);
    extern void registerFunctionDynamicElement(FunctionFactory & factory);
    extern void registerFunctionDynamicType(FunctionFactory & factory);
    extern void registerFunctionE(FunctionFactory & factory);
    extern void registerFunctionEmbeddedDictionaries(FunctionFactory & factory);
    extern void registerFunctionEmpty(FunctionFactory & factory);
    extern void registerFunctionEmptyArray(FunctionFactory & factory);
    extern void registerFunctionEmptyArrayToSingle(FunctionFactory & factory);
    extern void registerFunctionEncodeAndDecodeURLComponent(FunctionFactory & factory);
    extern void registerFunctionEncodeXMLComponent(FunctionFactory & factory);
    extern void registerFunctionEncrypt(FunctionFactory & factory);
    extern void registerFunctionEndsWith(FunctionFactory & factory);
    extern void registerFunctionEndsWithCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionEndsWithCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionEndsWithUTF8(FunctionFactory & factory);
    extern void registerFunctionEquals(FunctionFactory & factory);
    extern void registerFunctionErf(FunctionFactory & factory);
    extern void registerFunctionErfc(FunctionFactory & factory);
    extern void registerFunctionErrorCodeToName(FunctionFactory & factory);
    extern void registerFunctionEvalMLMethod(FunctionFactory & factory);
    extern void registerFunctionExp(FunctionFactory & factory);
    extern void registerFunctionExp10(FunctionFactory & factory);
    extern void registerFunctionExp2(FunctionFactory & factory);
    extern void registerFunctionExternalDictionaries(FunctionFactory & factory);
    extern void registerFunctionExtract(FunctionFactory & factory);
    extern void registerFunctionExtractAll(FunctionFactory & factory);
    extern void registerFunctionExtractAllGroupsHorizontal(FunctionFactory & factory);
    extern void registerFunctionExtractAllGroupsVertical(FunctionFactory & factory);
    extern void registerFunctionExtractGroups(FunctionFactory & factory);
    extern void registerFunctionExtractKeyValuePairs(FunctionFactory & factory);
    extern void registerFunctionExtractTextFromHTML(FunctionFactory & factory);
    extern void registerFunctionExtractURLParameter(FunctionFactory & factory);
    extern void registerFunctionExtractURLParameterNames(FunctionFactory & factory);
    extern void registerFunctionExtractURLParameters(FunctionFactory & factory);
    extern void registerFunctionFQDN(FunctionFactory & factory);
    extern void registerFunctionFactorial(FunctionFactory & factory);
    extern void registerFunctionFile(FunctionFactory & factory);
    extern void registerFunctionFilesystem(FunctionFactory & factory);
    extern void registerFunctionFilterContains(FunctionFactory & factory);
    extern void registerFunctionFinalizeAggregation(FunctionFactory & factory);
    extern void registerFunctionFirstLine(FunctionFactory & factory);
    extern void registerFunctionFirstNonDefault(FunctionFactory & factory);
    extern void registerFunctionFirstSignificantSubdomain(FunctionFactory & factory);
    extern void registerFunctionFirstSignificantSubdomainCustom(FunctionFactory & factory);
    extern void registerFunctionFixedString(FunctionFactory & factory);
    extern void registerFunctionFlattenTuple(FunctionFactory & factory);
    extern void registerFunctionFlipCoordinates(FunctionFactory & factory);
    extern void registerFunctionFormat(FunctionFactory & factory);
    extern void registerFunctionFormatDateTime(FunctionFactory & factory);
    extern void registerFunctionFormatReadableDecimalSize(FunctionFactory & factory);
    extern void registerFunctionFormatReadableQuantity(FunctionFactory & factory);
    extern void registerFunctionFormatReadableSize(FunctionFactory & factory);
    extern void registerFunctionFormatReadableTimeDelta(FunctionFactory & factory);
    extern void registerFunctionFormatRow(FunctionFactory & factory);
    extern void registerFunctionFragment(FunctionFactory & factory);
    extern void registerFunctionFromDaysSinceYearZero(FunctionFactory & factory);
    extern void registerFunctionFromModifiedJulianDay(FunctionFactory & factory);
    extern void registerFunctionFromUnixTimestamp64(FunctionFactory & factory);
    extern void registerFunctionFromUnixTimestamp64Micro(FunctionFactory & factory);
    extern void registerFunctionFromUnixTimestamp64Milli(FunctionFactory & factory);
    extern void registerFunctionFromUnixTimestamp64Nano(FunctionFactory & factory);
    extern void registerFunctionFunctionArrayExcept(FunctionFactory & factory);
    extern void registerFunctionFunctionColorOKLCHToSRGB(FunctionFactory & factory);
    extern void registerFunctionFunctionHMAC(FunctionFactory & factory);
    extern void registerFunctionFunctionIRR(FunctionFactory & factory);
    extern void registerFunctionFunctionNPV(FunctionFactory & factory);
    extern void registerFunctionFunctionXirr(FunctionFactory & factory);
    extern void registerFunctionFunctionXnpv(FunctionFactory & factory);
    extern void registerFunctionFuzzBits(FunctionFactory & factory);
    extern void registerFunctionGCD(FunctionFactory & factory);
    extern void registerFunctionGenerateRandomStructure(FunctionFactory & factory);
    extern void registerFunctionGenerateSnowflakeID(FunctionFactory & factory);
    extern void registerFunctionGenerateUUIDv4(FunctionFactory & factory);
    extern void registerFunctionGeoDistance(FunctionFactory & factory);
    extern void registerFunctionGeoToH3(FunctionFactory & factory);
    extern void registerFunctionGeohashDecode(FunctionFactory & factory);
    extern void registerFunctionGeohashEncode(FunctionFactory & factory);
    extern void registerFunctionGeohashesInBox(FunctionFactory & factory);
    extern void registerFunctionGetClientHTTPHeader(FunctionFactory & factory);
    extern void registerFunctionGetMacro(FunctionFactory & factory);
    extern void registerFunctionGetMergeTreeSetting(FunctionFactory & factory);
    extern void registerFunctionGetOSKernelVersion(FunctionFactory & factory);
    extern void registerFunctionGetScalar(FunctionFactory & factory);
    extern void registerFunctionGetServerPort(FunctionFactory & factory);
    extern void registerFunctionGetServerSetting(FunctionFactory & factory);
    extern void registerFunctionGetSetting(FunctionFactory & factory);
    extern void registerFunctionGetSizeOfEnumType(FunctionFactory & factory);
    extern void registerFunctionGetSubcolumn(FunctionFactory & factory);
    extern void registerFunctionGetTypeSerializationStreams(FunctionFactory & factory);
    extern void registerFunctionGlobalVariable(FunctionFactory & factory);
    extern void registerFunctionGreater(FunctionFactory & factory);
    extern void registerFunctionGreaterOrEquals(FunctionFactory & factory);
    extern void registerFunctionGreatest(FunctionFactory & factory);
    extern void registerFunctionH3CellAreaM2(FunctionFactory & factory);
    extern void registerFunctionH3CellAreaRads2(FunctionFactory & factory);
    extern void registerFunctionH3Distance(FunctionFactory & factory);
    extern void registerFunctionH3EdgeAngle(FunctionFactory & factory);
    extern void registerFunctionH3EdgeLengthKm(FunctionFactory & factory);
    extern void registerFunctionH3EdgeLengthM(FunctionFactory & factory);
    extern void registerFunctionH3ExactEdgeLengthKm(FunctionFactory & factory);
    extern void registerFunctionH3ExactEdgeLengthM(FunctionFactory & factory);
    extern void registerFunctionH3ExactEdgeLengthRads(FunctionFactory & factory);
    extern void registerFunctionH3GetBaseCell(FunctionFactory & factory);
    extern void registerFunctionH3GetDestinationIndexFromUnidirectionalEdge(FunctionFactory & factory);
    extern void registerFunctionH3GetFaces(FunctionFactory & factory);
    extern void registerFunctionH3GetIndexesFromUnidirectionalEdge(FunctionFactory & factory);
    extern void registerFunctionH3GetOriginIndexFromUnidirectionalEdge(FunctionFactory & factory);
    extern void registerFunctionH3GetPentagonIndexes(FunctionFactory & factory);
    extern void registerFunctionH3GetRes0Indexes(FunctionFactory & factory);
    extern void registerFunctionH3GetResolution(FunctionFactory & factory);
    extern void registerFunctionH3GetUnidirectionalEdge(FunctionFactory & factory);
    extern void registerFunctionH3GetUnidirectionalEdgeBoundary(FunctionFactory & factory);
    extern void registerFunctionH3GetUnidirectionalEdgesFromHexagon(FunctionFactory & factory);
    extern void registerFunctionH3HexAreaKm2(FunctionFactory & factory);
    extern void registerFunctionH3HexAreaM2(FunctionFactory & factory);
    extern void registerFunctionH3HexRing(FunctionFactory & factory);
    extern void registerFunctionH3IndexesAreNeighbors(FunctionFactory & factory);
    extern void registerFunctionH3IsPentagon(FunctionFactory & factory);
    extern void registerFunctionH3IsResClassIII(FunctionFactory & factory);
    extern void registerFunctionH3IsValid(FunctionFactory & factory);
    extern void registerFunctionH3KRing(FunctionFactory & factory);
    extern void registerFunctionH3Line(FunctionFactory & factory);
    extern void registerFunctionH3NumHexagons(FunctionFactory & factory);
    extern void registerFunctionH3PointDistKm(FunctionFactory & factory);
    extern void registerFunctionH3PointDistM(FunctionFactory & factory);
    extern void registerFunctionH3PointDistRads(FunctionFactory & factory);
    extern void registerFunctionH3PolygonToCells(FunctionFactory & factory);
    extern void registerFunctionH3ToCenterChild(FunctionFactory & factory);
    extern void registerFunctionH3ToChildren(FunctionFactory & factory);
    extern void registerFunctionH3ToGeo(FunctionFactory & factory);
    extern void registerFunctionH3ToGeoBoundary(FunctionFactory & factory);
    extern void registerFunctionH3ToParent(FunctionFactory & factory);
    extern void registerFunctionH3ToString(FunctionFactory & factory);
    extern void registerFunctionH3UnidirectionalEdgeIsValid(FunctionFactory & factory);
    extern void registerFunctionHas(FunctionFactory & factory);
    extern void registerFunctionHasAll(FunctionFactory & factory);
    extern void registerFunctionHasAllTokens(FunctionFactory & factory);
    extern void registerFunctionHasAny(FunctionFactory & factory);
    extern void registerFunctionHasAnyTokens(FunctionFactory & factory);
    extern void registerFunctionHasColumnInTable(FunctionFactory & factory);
    extern void registerFunctionHasSubstr(FunctionFactory & factory);
    extern void registerFunctionHasThreadFuzzer(FunctionFactory & factory);
    extern void registerFunctionHasToken(FunctionFactory & factory);
    extern void registerFunctionHasTokenCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionHashFixedStrings(FunctionFactory & factory);
    extern void registerFunctionHashing(FunctionFactory & factory);
    extern void registerFunctionHashingInt(FunctionFactory & factory);
    extern void registerFunctionHashingMurmur(FunctionFactory & factory);
    extern void registerFunctionHilbertDecode(FunctionFactory & factory);
    extern void registerFunctionHilbertEncode(FunctionFactory & factory);
    extern void registerFunctionHostName(FunctionFactory & factory);
    extern void registerFunctionHypot(FunctionFactory & factory);
    extern void registerFunctionILike(FunctionFactory & factory);
    extern void registerFunctionIcebergBucket(FunctionFactory & factory);
    extern void registerFunctionIcebergHash(FunctionFactory & factory);
    extern void registerFunctionIdentity(FunctionFactory & factory);
    extern void registerFunctionIf(FunctionFactory & factory);
    extern void registerFunctionIfNotFinite(FunctionFactory & factory);
    extern void registerFunctionIfNull(FunctionFactory & factory);
    extern void registerFunctionIgnore(FunctionFactory & factory);
    extern void registerFunctionIn(FunctionFactory & factory);
    extern void registerFunctionIndexHint(FunctionFactory & factory);
    extern void registerFunctionIndexOf(FunctionFactory & factory);
    extern void registerFunctionIndexOfAssumeSorted(FunctionFactory & factory);
    extern void registerFunctionInitcap(FunctionFactory & factory);
    extern void registerFunctionInitcapUTF8(FunctionFactory & factory);
    extern void registerFunctionInitialQueryID(FunctionFactory & factory);
    extern void registerFunctionInitialQueryStartTime(FunctionFactory & factory);
    extern void registerFunctionInitializeAggregation(FunctionFactory & factory);
    extern void registerFunctionIntDiv(FunctionFactory & factory);
    extern void registerFunctionIntDivOrNull(FunctionFactory & factory);
    extern void registerFunctionIntDivOrZero(FunctionFactory & factory);
    extern void registerFunctionIntExp10(FunctionFactory & factory);
    extern void registerFunctionIntExp2(FunctionFactory & factory);
    extern void registerFunctionIsConstant(FunctionFactory & factory);
    extern void registerFunctionIsDecimalOverflow(FunctionFactory & factory);
    extern void registerFunctionIsDistinctFrom(FunctionFactory & factory);
    extern void registerFunctionIsFinite(FunctionFactory & factory);
    extern void registerFunctionIsIPAddressContainedIn(FunctionFactory & factory);
    extern void registerFunctionIsInfinite(FunctionFactory & factory);
    extern void registerFunctionIsNaN(FunctionFactory & factory);
    extern void registerFunctionIsNotDistinctFrom(FunctionFactory & factory);
    extern void registerFunctionIsNotNull(FunctionFactory & factory);
    extern void registerFunctionIsNull(FunctionFactory & factory);
    extern void registerFunctionIsNullable(FunctionFactory & factory);
    extern void registerFunctionIsValidUTF8(FunctionFactory & factory);
    extern void registerFunctionIsZeroOrNull(FunctionFactory & factory);
    extern void registerFunctionJSON(FunctionFactory & factory);
    extern void registerFunctionJSONArrayLength(FunctionFactory & factory);
    extern void registerFunctionJSONExtractCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionJSONMergePatch(FunctionFactory & factory);
    extern void registerFunctionJSONPaths(FunctionFactory & factory);
    extern void registerFunctionJoinGet(FunctionFactory & factory);
    extern void registerFunctionJumpConsistentHash(FunctionFactory & factory);
    extern void registerFunctionKostikConsistentHash(FunctionFactory & factory);
    extern void registerFunctionKqlArraySort(FunctionFactory & factory);
    extern void registerFunctionLCM(FunctionFactory & factory);
    extern void registerFunctionLGamma(FunctionFactory & factory);
    extern void registerFunctionLeast(FunctionFactory & factory);
    extern void registerFunctionLeft(FunctionFactory & factory);
    extern void registerFunctionLegacySnowflakeConversion(FunctionFactory & factory);
    extern void registerFunctionLength(FunctionFactory & factory);
    extern void registerFunctionLengthUTF8(FunctionFactory & factory);
    extern void registerFunctionLess(FunctionFactory & factory);
    extern void registerFunctionLessOrEquals(FunctionFactory & factory);
    extern void registerFunctionLike(FunctionFactory & factory);
    extern void registerFunctionLocate(FunctionFactory & factory);
    extern void registerFunctionLog(FunctionFactory & factory);
    extern void registerFunctionLog10(FunctionFactory & factory);
    extern void registerFunctionLog1p(FunctionFactory & factory);
    extern void registerFunctionLog2(FunctionFactory & factory);
    extern void registerFunctionLogTrace(FunctionFactory & factory);
    extern void registerFunctionLogical(FunctionFactory & factory);
    extern void registerFunctionLowCardinalityIndices(FunctionFactory & factory);
    extern void registerFunctionLowCardinalityKeys(FunctionFactory & factory);
    extern void registerFunctionLower(FunctionFactory & factory);
    extern void registerFunctionMakeDate(FunctionFactory & factory);
    extern void registerFunctionMap(FunctionFactory & factory);
    extern void registerFunctionMapMiscellaneous(FunctionFactory & factory);
    extern void registerFunctionMapOp(FunctionFactory & factory);
    extern void registerFunctionMapPopulateSeries(FunctionFactory & factory);
    extern void registerFunctionMatch(FunctionFactory & factory);
    extern void registerFunctionMaterialize(FunctionFactory & factory);
    extern void registerFunctionMax2(FunctionFactory & factory);
    extern void registerFunctionMergeTreePartInfoTools(FunctionFactory & factory);
    extern void registerFunctionMidpoint(FunctionFactory & factory);
    extern void registerFunctionMin2(FunctionFactory & factory);
    extern void registerFunctionMinSampleSize(FunctionFactory & factory);
    extern void registerFunctionMinus(FunctionFactory & factory);
    extern void registerFunctionModulo(FunctionFactory & factory);
    extern void registerFunctionModuloLegacy(FunctionFactory & factory);
    extern void registerFunctionModuloOrNull(FunctionFactory & factory);
    extern void registerFunctionModuloOrZero(FunctionFactory & factory);
    extern void registerFunctionMonthName(FunctionFactory & factory);
    extern void registerFunctionMortonDecode(FunctionFactory & factory);
    extern void registerFunctionMortonEncode(FunctionFactory & factory);
    extern void registerFunctionMultiFuzzyMatchAllIndices(FunctionFactory & factory);
    extern void registerFunctionMultiFuzzyMatchAny(FunctionFactory & factory);
    extern void registerFunctionMultiFuzzyMatchAnyIndex(FunctionFactory & factory);
    extern void registerFunctionMultiIf(FunctionFactory & factory);
    extern void registerFunctionMultiMatchAllIndices(FunctionFactory & factory);
    extern void registerFunctionMultiMatchAny(FunctionFactory & factory);
    extern void registerFunctionMultiMatchAnyIndex(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAllPositions(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAllPositionsCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAllPositionsCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAllPositionsUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAny(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAnyCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAnyCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchAnyUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstIndex(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstIndexCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstIndexCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstIndexUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstPosition(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstPositionCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstPositionCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiSearchFirstPositionUTF8(FunctionFactory & factory);
    extern void registerFunctionMultiply(FunctionFactory & factory);
    extern void registerFunctionMultiplyDecimals(FunctionFactory & factory);
    extern void registerFunctionNaiveBayesClassifier(FunctionFactory & factory);
    extern void registerFunctionNegate(FunctionFactory & factory);
    extern void registerFunctionNeighbor(FunctionFactory & factory);
    extern void registerFunctionNested(FunctionFactory & factory);
    extern void registerFunctionNetloc(FunctionFactory & factory);
    extern void registerFunctionNgrams(FunctionFactory & factory);
    extern void registerFunctionNormalizeQuery(FunctionFactory & factory);
    extern void registerFunctionNormalizedGini(FunctionFactory & factory);
    extern void registerFunctionNormalizedQueryHash(FunctionFactory & factory);
    extern void registerFunctionNotEquals(FunctionFactory & factory);
    extern void registerFunctionNotILike(FunctionFactory & factory);
    extern void registerFunctionNotLike(FunctionFactory & factory);
    extern void registerFunctionNow(FunctionFactory & factory);
    extern void registerFunctionNow64(FunctionFactory & factory);
    extern void registerFunctionNowInBlock(FunctionFactory & factory);
    extern void registerFunctionNowInBlock64(FunctionFactory & factory);
    extern void registerFunctionNullIf(FunctionFactory & factory);
    extern void registerFunctionNumericIndexedVector(FunctionFactory & factory);
    extern void registerFunctionOverlay(FunctionFactory & factory);
    extern void registerFunctionPadString(FunctionFactory & factory);
    extern void registerFunctionParseDateTime(FunctionFactory & factory);
    extern void registerFunctionParseReadableSize(FunctionFactory & factory);
    extern void registerFunctionParseTimeDelta(FunctionFactory & factory);
    extern void registerFunctionPartitionId(FunctionFactory & factory);
    extern void registerFunctionPatchPartitionID(FunctionFactory & factory);
    extern void registerFunctionPath(FunctionFactory & factory);
    extern void registerFunctionPathFull(FunctionFactory & factory);
    extern void registerFunctionPerimeter(FunctionFactory & factory);
    extern void registerFunctionPi(FunctionFactory & factory);
    extern void registerFunctionPlus(FunctionFactory & factory);
    extern void registerFunctionPointInEllipses(FunctionFactory & factory);
    extern void registerFunctionPointInPolygon(FunctionFactory & factory);
    extern void registerFunctionPolygonArea(FunctionFactory & factory);
    extern void registerFunctionPolygonConvexHull(FunctionFactory & factory);
    extern void registerFunctionPolygonPerimeter(FunctionFactory & factory);
    extern void registerFunctionPolygonsDistance(FunctionFactory & factory);
    extern void registerFunctionPolygonsEquals(FunctionFactory & factory);
    extern void registerFunctionPolygonsIntersection(FunctionFactory & factory);
    extern void registerFunctionPolygonsSymDifference(FunctionFactory & factory);
    extern void registerFunctionPolygonsUnion(FunctionFactory & factory);
    extern void registerFunctionPolygonsWithin(FunctionFactory & factory);
    extern void registerFunctionPort(FunctionFactory & factory);
    extern void registerFunctionPosition(FunctionFactory & factory);
    extern void registerFunctionPositionCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionPositionCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionPositionUTF8(FunctionFactory & factory);
    extern void registerFunctionPositiveModulo(FunctionFactory & factory);
    extern void registerFunctionPositiveModuloOrNull(FunctionFactory & factory);
    extern void registerFunctionPow(FunctionFactory & factory);
    extern void registerFunctionPrintf(FunctionFactory & factory);
    extern void registerFunctionProfiles(FunctionFactory & factory);
    extern void registerFunctionProtocol(FunctionFactory & factory);
    extern void registerFunctionQueryID(FunctionFactory & factory);
    extern void registerFunctionQueryString(FunctionFactory & factory);
    extern void registerFunctionQueryStringAndFragment(FunctionFactory & factory);
    extern void registerFunctionRadians(FunctionFactory & factory);
    extern void registerFunctionRand(FunctionFactory & factory);
    extern void registerFunctionRand64(FunctionFactory & factory);
    extern void registerFunctionRandConstant(FunctionFactory & factory);
    extern void registerFunctionRandomFixedString(FunctionFactory & factory);
    extern void registerFunctionRandomPrintableASCII(FunctionFactory & factory);
    extern void registerFunctionRandomString(FunctionFactory & factory);
    extern void registerFunctionRandomStringUTF8(FunctionFactory & factory);
    extern void registerFunctionRange(FunctionFactory & factory);
    extern void registerFunctionReadWKB(FunctionFactory & factory);
    extern void registerFunctionReadWKT(FunctionFactory & factory);
    extern void registerFunctionRegexpExtract(FunctionFactory & factory);
    extern void registerFunctionRegexpQuoteMeta(FunctionFactory & factory);
    extern void registerFunctionReinterpretAs(FunctionFactory & factory);
    extern void registerFunctionRepeat(FunctionFactory & factory);
    extern void registerFunctionReplaceAll(FunctionFactory & factory);
    extern void registerFunctionReplaceOne(FunctionFactory & factory);
    extern void registerFunctionReplaceRegexpAll(FunctionFactory & factory);
    extern void registerFunctionReplaceRegexpOne(FunctionFactory & factory);
    extern void registerFunctionReplicate(FunctionFactory & factory);
    extern void registerFunctionReverse(FunctionFactory & factory);
    extern void registerFunctionReverseBySeparator(FunctionFactory & factory);
    extern void registerFunctionReverseUTF8(FunctionFactory & factory);
    extern void registerFunctionRevision(FunctionFactory & factory);
    extern void registerFunctionRight(FunctionFactory & factory);
    extern void registerFunctionRound(FunctionFactory & factory);
    extern void registerFunctionRoundAge(FunctionFactory & factory);
    extern void registerFunctionRoundDuration(FunctionFactory & factory);
    extern void registerFunctionRoundToExp2(FunctionFactory & factory);
    extern void registerFunctionRowNumberInAllBlocks(FunctionFactory & factory);
    extern void registerFunctionRowNumberInBlock(FunctionFactory & factory);
    extern void registerFunctionRunningAccumulate(FunctionFactory & factory);
    extern void registerFunctionRunningConcurrency(FunctionFactory & factory);
    extern void registerFunctionRunningDifference(FunctionFactory & factory);
    extern void registerFunctionRunningDifferenceStartingWithFirstValue(FunctionFactory & factory);
    extern void registerFunctionSQLJSON(FunctionFactory & factory);
    extern void registerFunctionScalarSubqueryResult(FunctionFactory & factory);
    extern void registerFunctionSerial(FunctionFactory & factory);
    extern void registerFunctionSeriesOutliersDetectTukey(FunctionFactory & factory);
    extern void registerFunctionServerTimezone(FunctionFactory & factory);
    extern void registerFunctionServerUUID(FunctionFactory & factory);
    extern void registerFunctionShowCertificate(FunctionFactory & factory);
    extern void registerFunctionSigmoid(FunctionFactory & factory);
    extern void registerFunctionSign(FunctionFactory & factory);
    extern void registerFunctionSin(FunctionFactory & factory);
    extern void registerFunctionSinh(FunctionFactory & factory);
    extern void registerFunctionSleep(FunctionFactory & factory);
    extern void registerFunctionSnowflakeIDToDateTime(FunctionFactory & factory);
    extern void registerFunctionSoundex(FunctionFactory & factory);
    extern void registerFunctionSpace(FunctionFactory & factory);
    extern void registerFunctionSparseGrams(FunctionFactory & factory);
    extern void registerFunctionSplitByAlpha(FunctionFactory & factory);
    extern void registerFunctionSplitByChar(FunctionFactory & factory);
    extern void registerFunctionSplitByNonAlpha(FunctionFactory & factory);
    extern void registerFunctionSplitByRegexp(FunctionFactory & factory);
    extern void registerFunctionSplitByString(FunctionFactory & factory);
    extern void registerFunctionSplitByWhitespace(FunctionFactory & factory);
    extern void registerFunctionSqrt(FunctionFactory & factory);
    extern void registerFunctionStartsWith(FunctionFactory & factory);
    extern void registerFunctionStartsWithCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionStartsWithCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionStartsWithUTF8(FunctionFactory & factory);
    extern void registerFunctionStringBytesEntropy(FunctionFactory & factory);
    extern void registerFunctionStringBytesUniq(FunctionFactory & factory);
    extern void registerFunctionStringDistance(FunctionFactory & factory);
    extern void registerFunctionStringHash(FunctionFactory & factory);
    extern void registerFunctionStringSimilarity(FunctionFactory & factory);
    extern void registerFunctionStringToH3(FunctionFactory & factory);
    extern void registerFunctionStructureToCapnProtoSchema(FunctionFactory & factory);
    extern void registerFunctionStructureToProtobufSchema(FunctionFactory & factory);
    extern void registerFunctionSubstring(FunctionFactory & factory);
    extern void registerFunctionSubstringIndex(FunctionFactory & factory);
    extern void registerFunctionSubtractDays(FunctionFactory & factory);
    extern void registerFunctionSubtractHours(FunctionFactory & factory);
    extern void registerFunctionSubtractMicroseconds(FunctionFactory & factory);
    extern void registerFunctionSubtractMilliseconds(FunctionFactory & factory);
    extern void registerFunctionSubtractMinutes(FunctionFactory & factory);
    extern void registerFunctionSubtractMonths(FunctionFactory & factory);
    extern void registerFunctionSubtractNanoseconds(FunctionFactory & factory);
    extern void registerFunctionSubtractQuarters(FunctionFactory & factory);
    extern void registerFunctionSubtractSeconds(FunctionFactory & factory);
    extern void registerFunctionSubtractWeeks(FunctionFactory & factory);
    extern void registerFunctionSubtractYears(FunctionFactory & factory);
    extern void registerFunctionSvg(FunctionFactory & factory);
    extern void registerFunctionTCPPort(FunctionFactory & factory);
    extern void registerFunctionTGamma(FunctionFactory & factory);
    extern void registerFunctionTan(FunctionFactory & factory);
    extern void registerFunctionTanh(FunctionFactory & factory);
    extern void registerFunctionThrowIf(FunctionFactory & factory);
    extern void registerFunctionTid(FunctionFactory & factory);
    extern void registerFunctionTimeDiff(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesCopyTag(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesCopyTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesExtractTag(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesFromGrid(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesGroupToTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesIdToGroup(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesIdToTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesJoinTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesRange(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesRemoveAllTagsExcept(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesRemoveTag(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesRemoveTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesReplaceTag(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesStoreTags(FunctionFactory & factory);
    extern void registerFunctionTimeSeriesTagsToGroup(FunctionFactory & factory);
    extern void registerFunctionTimeSlot(FunctionFactory & factory);
    extern void registerFunctionTimeSlots(FunctionFactory & factory);
    extern void registerFunctionTimeWindow(FunctionFactory & factory);
    extern void registerFunctionTimestamp(FunctionFactory & factory);
    extern void registerFunctionTimezone(FunctionFactory & factory);
    extern void registerFunctionTimezoneOf(FunctionFactory & factory);
    extern void registerFunctionToBool(FunctionFactory & factory);
    extern void registerFunctionToColumnTypeName(FunctionFactory & factory);
    extern void registerFunctionToCustomWeek(FunctionFactory & factory);
    extern void registerFunctionToDayOfMonth(FunctionFactory & factory);
    extern void registerFunctionToDayOfWeek(FunctionFactory & factory);
    extern void registerFunctionToDayOfYear(FunctionFactory & factory);
    extern void registerFunctionToDaysSinceYearZero(FunctionFactory & factory);
    extern void registerFunctionToDecimalString(FunctionFactory & factory);
    extern void registerFunctionToHour(FunctionFactory & factory);
    extern void registerFunctionToISOWeek(FunctionFactory & factory);
    extern void registerFunctionToISOYear(FunctionFactory & factory);
    extern void registerFunctionToInterval(FunctionFactory & factory);
    extern void registerFunctionToJSONString(FunctionFactory & factory);
    extern void registerFunctionToLastDayOfMonth(FunctionFactory & factory);
    extern void registerFunctionToLowCardinality(FunctionFactory & factory);
    extern void registerFunctionToMillisecond(FunctionFactory & factory);
    extern void registerFunctionToMinute(FunctionFactory & factory);
    extern void registerFunctionToModifiedJulianDay(FunctionFactory & factory);
    extern void registerFunctionToMonday(FunctionFactory & factory);
    extern void registerFunctionToMonth(FunctionFactory & factory);
    extern void registerFunctionToMonthNumSinceEpoch(FunctionFactory & factory);
    extern void registerFunctionToNullable(FunctionFactory & factory);
    extern void registerFunctionToQuarter(FunctionFactory & factory);
    extern void registerFunctionToRelativeDayNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeHourNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeMinuteNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeMonthNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeQuarterNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeSecondNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeWeekNum(FunctionFactory & factory);
    extern void registerFunctionToRelativeYearNum(FunctionFactory & factory);
    extern void registerFunctionToSecond(FunctionFactory & factory);
    extern void registerFunctionToStartOfDay(FunctionFactory & factory);
    extern void registerFunctionToStartOfFifteenMinutes(FunctionFactory & factory);
    extern void registerFunctionToStartOfFiveMinutes(FunctionFactory & factory);
    extern void registerFunctionToStartOfHour(FunctionFactory & factory);
    extern void registerFunctionToStartOfISOYear(FunctionFactory & factory);
    extern void registerFunctionToStartOfInterval(FunctionFactory & factory);
    extern void registerFunctionToStartOfMicrosecond(FunctionFactory & factory);
    extern void registerFunctionToStartOfMillisecond(FunctionFactory & factory);
    extern void registerFunctionToStartOfMinute(FunctionFactory & factory);
    extern void registerFunctionToStartOfMonth(FunctionFactory & factory);
    extern void registerFunctionToStartOfNanosecond(FunctionFactory & factory);
    extern void registerFunctionToStartOfQuarter(FunctionFactory & factory);
    extern void registerFunctionToStartOfSecond(FunctionFactory & factory);
    extern void registerFunctionToStartOfTenMinutes(FunctionFactory & factory);
    extern void registerFunctionToStartOfYear(FunctionFactory & factory);
    extern void registerFunctionToStringCutToZero(FunctionFactory & factory);
    extern void registerFunctionToTimeZone(FunctionFactory & factory);
    extern void registerFunctionToTypeName(FunctionFactory & factory);
    extern void registerFunctionToUnixTimestamp64Micro(FunctionFactory & factory);
    extern void registerFunctionToUnixTimestamp64Milli(FunctionFactory & factory);
    extern void registerFunctionToUnixTimestamp64Nano(FunctionFactory & factory);
    extern void registerFunctionToUnixTimestamp64Second(FunctionFactory & factory);
    extern void registerFunctionToValidUTF8(FunctionFactory & factory);
    extern void registerFunctionToYYYYMM(FunctionFactory & factory);
    extern void registerFunctionToYYYYMMDD(FunctionFactory & factory);
    extern void registerFunctionToYYYYMMDDhhmmss(FunctionFactory & factory);
    extern void registerFunctionToYear(FunctionFactory & factory);
    extern void registerFunctionToYearNumSinceEpoch(FunctionFactory & factory);
    extern void registerFunctionToday(FunctionFactory & factory);
    extern void registerFunctionTokens(FunctionFactory & factory);
    extern void registerFunctionTopLevelDomain(FunctionFactory & factory);
    extern void registerFunctionTransactionCounters(FunctionFactory & factory);
    extern void registerFunctionTransform(FunctionFactory & factory);
    extern void registerFunctionTranslate(FunctionFactory & factory);
    extern void registerFunctionTrim(FunctionFactory & factory);
    extern void registerFunctionTryBase32Decode(FunctionFactory & factory);
    extern void registerFunctionTryBase58Decode(FunctionFactory & factory);
    extern void registerFunctionTryDecrypt(FunctionFactory & factory);
    extern void registerFunctionTuple(FunctionFactory & factory);
    extern void registerFunctionTupleConcat(FunctionFactory & factory);
    extern void registerFunctionTupleElement(FunctionFactory & factory);
    extern void registerFunctionTupleHammingDistance(FunctionFactory & factory);
    extern void registerFunctionTupleNames(FunctionFactory & factory);
    extern void registerFunctionTupleToNameValuePairs(FunctionFactory & factory);
    extern void registerFunctionURLHierarchy(FunctionFactory & factory);
    extern void registerFunctionURLPathHierarchy(FunctionFactory & factory);
    extern void registerFunctionUTCTimestamp(FunctionFactory & factory);
    extern void registerFunctionUTCTimestampTransform(FunctionFactory & factory);
    extern void registerFunctionUpper(FunctionFactory & factory);
    extern void registerFunctionUptime(FunctionFactory & factory);
    extern void registerFunctionValidateNestedArraySizes(FunctionFactory & factory);
    extern void registerFunctionVariantElement(FunctionFactory & factory);
    extern void registerFunctionVariantType(FunctionFactory & factory);
    extern void registerFunctionVectorFunctions(FunctionFactory & factory);
    extern void registerFunctionVersion(FunctionFactory & factory);
    extern void registerFunctionVisibleWidth(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractBool(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractFloat(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractInt(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractRaw(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractString(FunctionFactory & factory);
    extern void registerFunctionVisitParamExtractUInt(FunctionFactory & factory);
    extern void registerFunctionVisitParamHas(FunctionFactory & factory);
    extern void registerFunctionWKB(FunctionFactory & factory);
    extern void registerFunctionWKT(FunctionFactory & factory);
    extern void registerFunctionWidthBucket(FunctionFactory & factory);
    extern void registerFunctionYesterday(FunctionFactory & factory);
    extern void registerFunctionZTest(FunctionFactory & factory);
    extern void registerFunctionZooKeeperSessionUptime(FunctionFactory & factory);
    extern void registerFunctionformatQuery(FunctionFactory & factory);
    extern void registerFunctionformatQueryOrNull(FunctionFactory & factory);
    extern void registerFunctionformatQuerySingleLine(FunctionFactory & factory);
    extern void registerFunctionformatQuerySingleLineOrNull(FunctionFactory & factory);
    extern void registerFunctiongetMaxTableName(FunctionFactory & factory);
    extern void registerFunctionhasSubsequence(FunctionFactory & factory);
    extern void registerFunctionhasSubsequenceCaseInsensitive(FunctionFactory & factory);
    extern void registerFunctionhasSubsequenceCaseInsensitiveUTF8(FunctionFactory & factory);
    extern void registerFunctionhasSubsequenceUTF8(FunctionFactory & factory);
    extern void registerFunctionpolygonsIntersect(FunctionFactory & factory);
    extern void registerFunctionseriesDecomposeSTL(FunctionFactory & factory);
    extern void registerFunctiontimezoneOffset(FunctionFactory & factory);

    /// Force references to ensure function registration functions are linked
    void * ForceStaticRegistrationObjects()
    {
        /// Create function pointer array to force linking
        static void (*registration_funcs[])(FunctionFactory &) =
        {
            &::registerFunctionIsValidASCII,
            &registerFunctionAESDecryptMysql,
            &registerFunctionAESEncryptMysql,
            &registerFunctionAbs,
            &registerFunctionAcos,
            &registerFunctionAcosh,
            &registerFunctionActionName,
            &registerFunctionAddDays,
            &registerFunctionAddHours,
            &registerFunctionAddInterval,
            &registerFunctionAddMicroseconds,
            &registerFunctionAddMilliseconds,
            &registerFunctionAddMinutes,
            &registerFunctionAddMonths,
            &registerFunctionAddNanoseconds,
            &registerFunctionAddQuarters,
            &registerFunctionAddSeconds,
            &registerFunctionAddWeeks,
            &registerFunctionAddYears,
            &registerFunctionAge,
            &registerFunctionAppendTrailingCharIfAbsent,
            &registerFunctionArea,
            &registerFunctionArray,
            &registerFunctionArrayAUC,
            &registerFunctionArrayAggregation,
            &registerFunctionArrayAll,
            &registerFunctionArrayCompact,
            &registerFunctionArrayConcat,
            &registerFunctionArrayCount,
            &registerFunctionArrayCumSum,
            &registerFunctionArrayCumSumNonNegative,
            &registerFunctionArrayDifference,
            &registerFunctionArrayDistinct,
            &registerFunctionArrayDotProduct,
            &registerFunctionArrayElement,
            &registerFunctionArrayEnumerate,
            &registerFunctionArrayEnumerateDense,
            &registerFunctionArrayEnumerateDenseRanked,
            &registerFunctionArrayEnumerateUniq,
            &registerFunctionArrayEnumerateUniqRanked,
            &registerFunctionArrayExists,
            &registerFunctionArrayFill,
            &registerFunctionArrayFilter,
            &registerFunctionArrayFirst,
            &registerFunctionArrayFirstIndex,
            &registerFunctionArrayFlatten,
            &registerFunctionArrayFold,
            &registerFunctionArrayIntersect,
            &registerFunctionArrayJaccardIndex,
            &registerFunctionArrayJoin,
            &registerFunctionArrayLevenshtein,
            &registerFunctionArrayMap,
            &registerFunctionArrayPopBack,
            &registerFunctionArrayPopFront,
            &registerFunctionArrayPushBack,
            &registerFunctionArrayPushFront,
            &registerFunctionArrayRandomSample,
            &registerFunctionArrayReduce,
            &registerFunctionArrayReduceInRanges,
            &registerFunctionArrayRemove,
            &registerFunctionArrayResize,
            &registerFunctionArrayReverse,
            &registerFunctionArrayShiftOrRotate,
            &registerFunctionArrayShingles,
            &registerFunctionArrayShuffle,
            &registerFunctionArraySlice,
            &registerFunctionArraySort,
            &registerFunctionArraySplit,
            &registerFunctionArrayStringConcat,
            &registerFunctionArrayUniq,
            &registerFunctionArrayWithConstant,
            &registerFunctionArrayZip,
            &registerFunctionAscii,
            &registerFunctionAsin,
            &registerFunctionAsinh,
            &registerFunctionAssumeNotNull,
            &registerFunctionAtan,
            &registerFunctionAtan2,
            &registerFunctionAtanh,
            &registerFunctionAuthenticatedUser,
            &registerFunctionAvg2,
            &registerFunctionBar,
            &registerFunctionBase32Decode,
            &registerFunctionBase32Encode,
            &registerFunctionBase58Decode,
            &registerFunctionBase58Encode,
            &registerFunctionBasename,
            &registerFunctionBinaryRepr,
            &registerFunctionBitAnd,
            &registerFunctionBitBoolMaskAnd,
            &registerFunctionBitBoolMaskOr,
            &registerFunctionBitCount,
            &registerFunctionBitHammingDistance,
            &registerFunctionBitNot,
            &registerFunctionBitOr,
            &registerFunctionBitRotateLeft,
            &registerFunctionBitRotateRight,
            &registerFunctionBitShiftLeft,
            &registerFunctionBitShiftRight,
            &registerFunctionBitSlice,
            &registerFunctionBitSwapLastTwo,
            &registerFunctionBitTest,
            &registerFunctionBitTestAll,
            &registerFunctionBitTestAny,
            &registerFunctionBitToArray,
            &registerFunctionBitWrapperFunc,
            &registerFunctionBitXor,
            &registerFunctionBitmap,
            &registerFunctionBlockNumber,
            &registerFunctionBlockSerializedSize,
            &registerFunctionBlockSize,
            &registerFunctionByteSize,
            &registerFunctionByteSwap,
            &registerFunctionCRC,
            &registerFunctionCanonicalRand,
            &registerFunctionCaseWithExpression,
            &registerFunctionCastOrDefault,
            &registerFunctionCastOverloadResolvers,
            &registerFunctionCatBoostEvaluate,
            &registerFunctionCbrt,
            &registerFunctionChangeDate,
            &registerFunctionChar,
            &registerFunctionChdbVersion,
            &registerFunctionClamp,
            &registerFunctionCoalesce,
            &registerFunctionCoding,
            &registerFunctionCodingUUID,
            &registerFunctionColorSRGBToOKLCH,
            &registerFunctionCompareSubstrings,
            &registerFunctionConcat,
            &registerFunctionConcatWithSeparator,
            &registerFunctionConnectionId,
            &registerFunctionConv,
            &registerFunctionConversion,
            &registerFunctionCos,
            &registerFunctionCosh,
            &registerFunctionCountDigits,
            &registerFunctionCountEqual,
            &registerFunctionCountMatches,
            &registerFunctionCountSubstrings,
            &registerFunctionCountSubstringsCaseInsensitive,
            &registerFunctionCountSubstringsCaseInsensitiveUTF8,
            &registerFunctionCurrentDatabase,
            &registerFunctionCurrentQueryID,
            &registerFunctionCurrentRoles,
            &registerFunctionCurrentSchema,
            &registerFunctionCurrentUser,
            &registerFunctionCutFragment,
            &registerFunctionCutQueryString,
            &registerFunctionCutQueryStringAndFragment,
            &registerFunctionCutToFirstSignificantSubdomain,
            &registerFunctionCutToFirstSignificantSubdomainCustom,
            &registerFunctionCutURLParameter,
            &registerFunctionCutWWW,
            &registerFunctionDateDiff,
            &registerFunctionDateName,
            &registerFunctionDateTimeToSnowflakeID,
            &registerFunctionDateTrunc,
            &registerFunctionDecodeHTMLComponent,
            &registerFunctionDecodeXMLComponent,
            &registerFunctionDecrypt,
            &registerFunctionDefaultValueOfArgumentType,
            &registerFunctionDefaultValueOfTypeName,
            &registerFunctionDegrees,
            &registerFunctionDemangle,
            &registerFunctionDictGetKeys,
            &registerFunctionDisplayName,
            &registerFunctionDistribution,
            &registerFunctionDivide,
            &registerFunctionDivideDecimals,
            &registerFunctionDivideOrNull,
            &registerFunctionDomain,
            &registerFunctionDomainWithoutWWW,
            &registerFunctionDumpColumnStructure,
            &registerFunctionDynamicElement,
            &registerFunctionDynamicType,
            &registerFunctionE,
            &registerFunctionEmbeddedDictionaries,
            &registerFunctionEmpty,
            &registerFunctionEmptyArray,
            &registerFunctionEmptyArrayToSingle,
            &registerFunctionEncodeAndDecodeURLComponent,
            &registerFunctionEncodeXMLComponent,
            &registerFunctionEncrypt,
            &registerFunctionEndsWith,
            &registerFunctionEndsWithCaseInsensitive,
            &registerFunctionEndsWithCaseInsensitiveUTF8,
            &registerFunctionEndsWithUTF8,
            &registerFunctionEquals,
            &registerFunctionErf,
            &registerFunctionErfc,
            &registerFunctionErrorCodeToName,
            &registerFunctionEvalMLMethod,
            &registerFunctionExp,
            &registerFunctionExp10,
            &registerFunctionExp2,
            &registerFunctionExternalDictionaries,
            &registerFunctionExtract,
            &registerFunctionExtractAll,
            &registerFunctionExtractAllGroupsHorizontal,
            &registerFunctionExtractAllGroupsVertical,
            &registerFunctionExtractGroups,
            &registerFunctionExtractKeyValuePairs,
            &registerFunctionExtractTextFromHTML,
            &registerFunctionExtractURLParameter,
            &registerFunctionExtractURLParameterNames,
            &registerFunctionExtractURLParameters,
            &registerFunctionFQDN,
            &registerFunctionFactorial,
            &registerFunctionFile,
            &registerFunctionFilesystem,
            &registerFunctionFilterContains,
            &registerFunctionFinalizeAggregation,
            &registerFunctionFirstLine,
            &registerFunctionFirstNonDefault,
            &registerFunctionFirstSignificantSubdomain,
            &registerFunctionFirstSignificantSubdomainCustom,
            &registerFunctionFixedString,
            &registerFunctionFlattenTuple,
            &registerFunctionFlipCoordinates,
            &registerFunctionFormat,
            &registerFunctionFormatDateTime,
            &registerFunctionFormatReadableDecimalSize,
            &registerFunctionFormatReadableQuantity,
            &registerFunctionFormatReadableSize,
            &registerFunctionFormatReadableTimeDelta,
            &registerFunctionFormatRow,
            &registerFunctionFragment,
            &registerFunctionFromDaysSinceYearZero,
            &registerFunctionFromModifiedJulianDay,
            &registerFunctionFromUnixTimestamp64,
            &registerFunctionFromUnixTimestamp64Micro,
            &registerFunctionFromUnixTimestamp64Milli,
            &registerFunctionFromUnixTimestamp64Nano,
            &registerFunctionFunctionArrayExcept,
            &registerFunctionFunctionColorOKLCHToSRGB,
            &registerFunctionFunctionHMAC,
            &registerFunctionFunctionIRR,
            &registerFunctionFunctionNPV,
            &registerFunctionFunctionXirr,
            &registerFunctionFunctionXnpv,
            &registerFunctionFuzzBits,
            &registerFunctionGCD,
            &registerFunctionGenerateRandomStructure,
            &registerFunctionGenerateSnowflakeID,
            &registerFunctionGenerateUUIDv4,
            &registerFunctionGeoDistance,
            &registerFunctionGeoToH3,
            &registerFunctionGeohashDecode,
            &registerFunctionGeohashEncode,
            &registerFunctionGeohashesInBox,
            &registerFunctionGetClientHTTPHeader,
            &registerFunctionGetMacro,
            &registerFunctionGetMergeTreeSetting,
            &registerFunctionGetOSKernelVersion,
            &registerFunctionGetScalar,
            &registerFunctionGetServerPort,
            &registerFunctionGetServerSetting,
            &registerFunctionGetSetting,
            &registerFunctionGetSizeOfEnumType,
            &registerFunctionGetSubcolumn,
            &registerFunctionGetTypeSerializationStreams,
            &registerFunctionGlobalVariable,
            &registerFunctionGreater,
            &registerFunctionGreaterOrEquals,
            &registerFunctionGreatest,
            &registerFunctionH3CellAreaM2,
            &registerFunctionH3CellAreaRads2,
            &registerFunctionH3Distance,
            &registerFunctionH3EdgeAngle,
            &registerFunctionH3EdgeLengthKm,
            &registerFunctionH3EdgeLengthM,
            &registerFunctionH3ExactEdgeLengthKm,
            &registerFunctionH3ExactEdgeLengthM,
            &registerFunctionH3ExactEdgeLengthRads,
            &registerFunctionH3GetBaseCell,
            &registerFunctionH3GetDestinationIndexFromUnidirectionalEdge,
            &registerFunctionH3GetFaces,
            &registerFunctionH3GetIndexesFromUnidirectionalEdge,
            &registerFunctionH3GetOriginIndexFromUnidirectionalEdge,
            &registerFunctionH3GetPentagonIndexes,
            &registerFunctionH3GetRes0Indexes,
            &registerFunctionH3GetResolution,
            &registerFunctionH3GetUnidirectionalEdge,
            &registerFunctionH3GetUnidirectionalEdgeBoundary,
            &registerFunctionH3GetUnidirectionalEdgesFromHexagon,
            &registerFunctionH3HexAreaKm2,
            &registerFunctionH3HexAreaM2,
            &registerFunctionH3HexRing,
            &registerFunctionH3IndexesAreNeighbors,
            &registerFunctionH3IsPentagon,
            &registerFunctionH3IsResClassIII,
            &registerFunctionH3IsValid,
            &registerFunctionH3KRing,
            &registerFunctionH3Line,
            &registerFunctionH3NumHexagons,
            &registerFunctionH3PointDistKm,
            &registerFunctionH3PointDistM,
            &registerFunctionH3PointDistRads,
            &registerFunctionH3PolygonToCells,
            &registerFunctionH3ToCenterChild,
            &registerFunctionH3ToChildren,
            &registerFunctionH3ToGeo,
            &registerFunctionH3ToGeoBoundary,
            &registerFunctionH3ToParent,
            &registerFunctionH3ToString,
            &registerFunctionH3UnidirectionalEdgeIsValid,
            &registerFunctionHas,
            &registerFunctionHasAll,
            &registerFunctionHasAllTokens,
            &registerFunctionHasAny,
            &registerFunctionHasAnyTokens,
            &registerFunctionHasColumnInTable,
            &registerFunctionHasSubstr,
            &registerFunctionHasThreadFuzzer,
            &registerFunctionHasToken,
            &registerFunctionHasTokenCaseInsensitive,
            &registerFunctionHashFixedStrings,
            &registerFunctionHashing,
            &registerFunctionHashingInt,
            &registerFunctionHashingMurmur,
            &registerFunctionHilbertDecode,
            &registerFunctionHilbertEncode,
            &registerFunctionHostName,
            &registerFunctionHypot,
            &registerFunctionILike,
            &registerFunctionIcebergBucket,
            &registerFunctionIcebergHash,
            &registerFunctionIdentity,
            &registerFunctionIf,
            &registerFunctionIfNotFinite,
            &registerFunctionIfNull,
            &registerFunctionIgnore,
            &registerFunctionIn,
            &registerFunctionIndexHint,
            &registerFunctionIndexOf,
            &registerFunctionIndexOfAssumeSorted,
            &registerFunctionInitcap,
            &registerFunctionInitcapUTF8,
            &registerFunctionInitialQueryID,
            &registerFunctionInitialQueryStartTime,
            &registerFunctionInitializeAggregation,
            &registerFunctionIntDiv,
            &registerFunctionIntDivOrNull,
            &registerFunctionIntDivOrZero,
            &registerFunctionIntExp10,
            &registerFunctionIntExp2,
            &registerFunctionIsConstant,
            &registerFunctionIsDecimalOverflow,
            &registerFunctionIsDistinctFrom,
            &registerFunctionIsFinite,
            &registerFunctionIsIPAddressContainedIn,
            &registerFunctionIsInfinite,
            &registerFunctionIsNaN,
            &registerFunctionIsNotDistinctFrom,
            &registerFunctionIsNotNull,
            &registerFunctionIsNull,
            &registerFunctionIsNullable,
            &registerFunctionIsValidUTF8,
            &registerFunctionIsZeroOrNull,
            &registerFunctionJSON,
            &registerFunctionJSONArrayLength,
            &registerFunctionJSONExtractCaseInsensitive,
            &registerFunctionJSONMergePatch,
            &registerFunctionJSONPaths,
            &registerFunctionJoinGet,
            &registerFunctionJumpConsistentHash,
            &registerFunctionKostikConsistentHash,
            &registerFunctionKqlArraySort,
            &registerFunctionLCM,
            &registerFunctionLGamma,
            &registerFunctionLeast,
            &registerFunctionLeft,
            &registerFunctionLegacySnowflakeConversion,
            &registerFunctionLength,
            &registerFunctionLengthUTF8,
            &registerFunctionLess,
            &registerFunctionLessOrEquals,
            &registerFunctionLike,
            &registerFunctionLocate,
            &registerFunctionLog,
            &registerFunctionLog10,
            &registerFunctionLog1p,
            &registerFunctionLog2,
            &registerFunctionLogTrace,
            &registerFunctionLogical,
            &registerFunctionLowCardinalityIndices,
            &registerFunctionLowCardinalityKeys,
            &registerFunctionLower,
            &registerFunctionMakeDate,
            &registerFunctionMap,
            &registerFunctionMapMiscellaneous,
            &registerFunctionMapOp,
            &registerFunctionMapPopulateSeries,
            &registerFunctionMatch,
            &registerFunctionMaterialize,
            &registerFunctionMax2,
            &registerFunctionMergeTreePartInfoTools,
            &registerFunctionMidpoint,
            &registerFunctionMin2,
            &registerFunctionMinSampleSize,
            &registerFunctionMinus,
            &registerFunctionModulo,
            &registerFunctionModuloLegacy,
            &registerFunctionModuloOrNull,
            &registerFunctionModuloOrZero,
            &registerFunctionMonthName,
            &registerFunctionMortonDecode,
            &registerFunctionMortonEncode,
            &registerFunctionMultiFuzzyMatchAllIndices,
            &registerFunctionMultiFuzzyMatchAny,
            &registerFunctionMultiFuzzyMatchAnyIndex,
            &registerFunctionMultiIf,
            &registerFunctionMultiMatchAllIndices,
            &registerFunctionMultiMatchAny,
            &registerFunctionMultiMatchAnyIndex,
            &registerFunctionMultiSearchAllPositions,
            &registerFunctionMultiSearchAllPositionsCaseInsensitive,
            &registerFunctionMultiSearchAllPositionsCaseInsensitiveUTF8,
            &registerFunctionMultiSearchAllPositionsUTF8,
            &registerFunctionMultiSearchAny,
            &registerFunctionMultiSearchAnyCaseInsensitive,
            &registerFunctionMultiSearchAnyCaseInsensitiveUTF8,
            &registerFunctionMultiSearchAnyUTF8,
            &registerFunctionMultiSearchFirstIndex,
            &registerFunctionMultiSearchFirstIndexCaseInsensitive,
            &registerFunctionMultiSearchFirstIndexCaseInsensitiveUTF8,
            &registerFunctionMultiSearchFirstIndexUTF8,
            &registerFunctionMultiSearchFirstPosition,
            &registerFunctionMultiSearchFirstPositionCaseInsensitive,
            &registerFunctionMultiSearchFirstPositionCaseInsensitiveUTF8,
            &registerFunctionMultiSearchFirstPositionUTF8,
            &registerFunctionMultiply,
            &registerFunctionMultiplyDecimals,
            &registerFunctionNaiveBayesClassifier,
            &registerFunctionNegate,
            &registerFunctionNeighbor,
            &registerFunctionNested,
            &registerFunctionNetloc,
            &registerFunctionNgrams,
            &registerFunctionNormalizeQuery,
            &registerFunctionNormalizedGini,
            &registerFunctionNormalizedQueryHash,
            &registerFunctionNotEquals,
            &registerFunctionNotILike,
            &registerFunctionNotLike,
            &registerFunctionNow,
            &registerFunctionNow64,
            &registerFunctionNowInBlock,
            &registerFunctionNowInBlock64,
            &registerFunctionNullIf,
            &registerFunctionNumericIndexedVector,
            &registerFunctionOverlay,
            &registerFunctionPadString,
            &registerFunctionParseDateTime,
            &registerFunctionParseReadableSize,
            &registerFunctionParseTimeDelta,
            &registerFunctionPartitionId,
            &registerFunctionPatchPartitionID,
            &registerFunctionPath,
            &registerFunctionPathFull,
            &registerFunctionPerimeter,
            &registerFunctionPi,
            &registerFunctionPlus,
            &registerFunctionPointInEllipses,
            &registerFunctionPointInPolygon,
            &registerFunctionPolygonArea,
            &registerFunctionPolygonConvexHull,
            &registerFunctionPolygonPerimeter,
            &registerFunctionPolygonsDistance,
            &registerFunctionPolygonsEquals,
            &registerFunctionPolygonsIntersection,
            &registerFunctionPolygonsSymDifference,
            &registerFunctionPolygonsUnion,
            &registerFunctionPolygonsWithin,
            &registerFunctionPort,
            &registerFunctionPosition,
            &registerFunctionPositionCaseInsensitive,
            &registerFunctionPositionCaseInsensitiveUTF8,
            &registerFunctionPositionUTF8,
            &registerFunctionPositiveModulo,
            &registerFunctionPositiveModuloOrNull,
            &registerFunctionPow,
            &registerFunctionPrintf,
            &registerFunctionProfiles,
            &registerFunctionProtocol,
            &registerFunctionQueryID,
            &registerFunctionQueryString,
            &registerFunctionQueryStringAndFragment,
            &registerFunctionRadians,
            &registerFunctionRand,
            &registerFunctionRand64,
            &registerFunctionRandConstant,
            &registerFunctionRandomFixedString,
            &registerFunctionRandomPrintableASCII,
            &registerFunctionRandomString,
            &registerFunctionRandomStringUTF8,
            &registerFunctionRange,
            &registerFunctionReadWKB,
            &registerFunctionReadWKT,
            &registerFunctionRegexpExtract,
            &registerFunctionRegexpQuoteMeta,
            &registerFunctionReinterpretAs,
            &registerFunctionRepeat,
            &registerFunctionReplaceAll,
            &registerFunctionReplaceOne,
            &registerFunctionReplaceRegexpAll,
            &registerFunctionReplaceRegexpOne,
            &registerFunctionReplicate,
            &registerFunctionReverse,
            &registerFunctionReverseBySeparator,
            &registerFunctionReverseUTF8,
            &registerFunctionRevision,
            &registerFunctionRight,
            &registerFunctionRound,
            &registerFunctionRoundAge,
            &registerFunctionRoundDuration,
            &registerFunctionRoundToExp2,
            &registerFunctionRowNumberInAllBlocks,
            &registerFunctionRowNumberInBlock,
            &registerFunctionRunningAccumulate,
            &registerFunctionRunningConcurrency,
            &registerFunctionRunningDifference,
            &registerFunctionRunningDifferenceStartingWithFirstValue,
            &registerFunctionSQLJSON,
            &registerFunctionScalarSubqueryResult,
            &registerFunctionSerial,
            &registerFunctionSeriesOutliersDetectTukey,
            &registerFunctionServerTimezone,
            &registerFunctionServerUUID,
            &registerFunctionShowCertificate,
            &registerFunctionSigmoid,
            &registerFunctionSign,
            &registerFunctionSin,
            &registerFunctionSinh,
            &registerFunctionSleep,
            &registerFunctionSnowflakeIDToDateTime,
            &registerFunctionSoundex,
            &registerFunctionSpace,
            &registerFunctionSparseGrams,
            &registerFunctionSplitByAlpha,
            &registerFunctionSplitByChar,
            &registerFunctionSplitByNonAlpha,
            &registerFunctionSplitByRegexp,
            &registerFunctionSplitByString,
            &registerFunctionSplitByWhitespace,
            &registerFunctionSqrt,
            &registerFunctionStartsWith,
            &registerFunctionStartsWithCaseInsensitive,
            &registerFunctionStartsWithCaseInsensitiveUTF8,
            &registerFunctionStartsWithUTF8,
            &registerFunctionStringBytesEntropy,
            &registerFunctionStringBytesUniq,
            &registerFunctionStringDistance,
            &registerFunctionStringHash,
            &registerFunctionStringSimilarity,
            &registerFunctionStringToH3,
            &registerFunctionStructureToCapnProtoSchema,
            &registerFunctionStructureToProtobufSchema,
            &registerFunctionSubstring,
            &registerFunctionSubstringIndex,
            &registerFunctionSubtractDays,
            &registerFunctionSubtractHours,
            &registerFunctionSubtractMicroseconds,
            &registerFunctionSubtractMilliseconds,
            &registerFunctionSubtractMinutes,
            &registerFunctionSubtractMonths,
            &registerFunctionSubtractNanoseconds,
            &registerFunctionSubtractQuarters,
            &registerFunctionSubtractSeconds,
            &registerFunctionSubtractWeeks,
            &registerFunctionSubtractYears,
            &registerFunctionSvg,
            &registerFunctionTCPPort,
            &registerFunctionTGamma,
            &registerFunctionTan,
            &registerFunctionTanh,
            &registerFunctionThrowIf,
            &registerFunctionTid,
            &registerFunctionTimeDiff,
            &registerFunctionTimeSeriesCopyTag,
            &registerFunctionTimeSeriesCopyTags,
            &registerFunctionTimeSeriesExtractTag,
            &registerFunctionTimeSeriesFromGrid,
            &registerFunctionTimeSeriesGroupToTags,
            &registerFunctionTimeSeriesIdToGroup,
            &registerFunctionTimeSeriesIdToTags,
            &registerFunctionTimeSeriesJoinTags,
            &registerFunctionTimeSeriesRange,
            &registerFunctionTimeSeriesRemoveAllTagsExcept,
            &registerFunctionTimeSeriesRemoveTag,
            &registerFunctionTimeSeriesRemoveTags,
            &registerFunctionTimeSeriesReplaceTag,
            &registerFunctionTimeSeriesStoreTags,
            &registerFunctionTimeSeriesTagsToGroup,
            &registerFunctionTimeSlot,
            &registerFunctionTimeSlots,
            &registerFunctionTimeWindow,
            &registerFunctionTimestamp,
            &registerFunctionTimezone,
            &registerFunctionTimezoneOf,
            &registerFunctionToBool,
            &registerFunctionToColumnTypeName,
            &registerFunctionToCustomWeek,
            &registerFunctionToDayOfMonth,
            &registerFunctionToDayOfWeek,
            &registerFunctionToDayOfYear,
            &registerFunctionToDaysSinceYearZero,
            &registerFunctionToDecimalString,
            &registerFunctionToHour,
            &registerFunctionToISOWeek,
            &registerFunctionToISOYear,
            &registerFunctionToInterval,
            &registerFunctionToJSONString,
            &registerFunctionToLastDayOfMonth,
            &registerFunctionToLowCardinality,
            &registerFunctionToMillisecond,
            &registerFunctionToMinute,
            &registerFunctionToModifiedJulianDay,
            &registerFunctionToMonday,
            &registerFunctionToMonth,
            &registerFunctionToMonthNumSinceEpoch,
            &registerFunctionToNullable,
            &registerFunctionToQuarter,
            &registerFunctionToRelativeDayNum,
            &registerFunctionToRelativeHourNum,
            &registerFunctionToRelativeMinuteNum,
            &registerFunctionToRelativeMonthNum,
            &registerFunctionToRelativeQuarterNum,
            &registerFunctionToRelativeSecondNum,
            &registerFunctionToRelativeWeekNum,
            &registerFunctionToRelativeYearNum,
            &registerFunctionToSecond,
            &registerFunctionToStartOfDay,
            &registerFunctionToStartOfFifteenMinutes,
            &registerFunctionToStartOfFiveMinutes,
            &registerFunctionToStartOfHour,
            &registerFunctionToStartOfISOYear,
            &registerFunctionToStartOfInterval,
            &registerFunctionToStartOfMicrosecond,
            &registerFunctionToStartOfMillisecond,
            &registerFunctionToStartOfMinute,
            &registerFunctionToStartOfMonth,
            &registerFunctionToStartOfNanosecond,
            &registerFunctionToStartOfQuarter,
            &registerFunctionToStartOfSecond,
            &registerFunctionToStartOfTenMinutes,
            &registerFunctionToStartOfYear,
            &registerFunctionToStringCutToZero,
            &registerFunctionToTimeZone,
            &registerFunctionToTypeName,
            &registerFunctionToUnixTimestamp64Micro,
            &registerFunctionToUnixTimestamp64Milli,
            &registerFunctionToUnixTimestamp64Nano,
            &registerFunctionToUnixTimestamp64Second,
            &registerFunctionToValidUTF8,
            &registerFunctionToYYYYMM,
            &registerFunctionToYYYYMMDD,
            &registerFunctionToYYYYMMDDhhmmss,
            &registerFunctionToYear,
            &registerFunctionToYearNumSinceEpoch,
            &registerFunctionToday,
            &registerFunctionTokens,
            &registerFunctionTopLevelDomain,
            &registerFunctionTransactionCounters,
            &registerFunctionTransform,
            &registerFunctionTranslate,
            &registerFunctionTrim,
            &registerFunctionTryBase32Decode,
            &registerFunctionTryBase58Decode,
            &registerFunctionTryDecrypt,
            &registerFunctionTuple,
            &registerFunctionTupleConcat,
            &registerFunctionTupleElement,
            &registerFunctionTupleHammingDistance,
            &registerFunctionTupleNames,
            &registerFunctionTupleToNameValuePairs,
            &registerFunctionURLHierarchy,
            &registerFunctionURLPathHierarchy,
            &registerFunctionUTCTimestamp,
            &registerFunctionUTCTimestampTransform,
            &registerFunctionUpper,
            &registerFunctionUptime,
            &registerFunctionValidateNestedArraySizes,
            &registerFunctionVariantElement,
            &registerFunctionVariantType,
            &registerFunctionVectorFunctions,
            &registerFunctionVersion,
            &registerFunctionVisibleWidth,
            &registerFunctionVisitParamExtractBool,
            &registerFunctionVisitParamExtractFloat,
            &registerFunctionVisitParamExtractInt,
            &registerFunctionVisitParamExtractRaw,
            &registerFunctionVisitParamExtractString,
            &registerFunctionVisitParamExtractUInt,
            &registerFunctionVisitParamHas,
            &registerFunctionWKB,
            &registerFunctionWKT,
            &registerFunctionWidthBucket,
            &registerFunctionYesterday,
            &registerFunctionZTest,
            &registerFunctionZooKeeperSessionUptime,
            &registerFunctionformatQuery,
            &registerFunctionformatQueryOrNull,
            &registerFunctionformatQuerySingleLine,
            &registerFunctionformatQuerySingleLineOrNull,
            &registerFunctiongetMaxTableName,
            &registerFunctionhasSubsequence,
            &registerFunctionhasSubsequenceCaseInsensitive,
            &registerFunctionhasSubsequenceCaseInsensitiveUTF8,
            &registerFunctionhasSubsequenceUTF8,
            &registerFunctionpolygonsIntersect,
            &registerFunctionseriesDecomposeSTL,
            &registerFunctiontimezoneOffset,
            nullptr
        };

        /// Return pointer to prevent compiler optimization
        return static_cast<void *>(registration_funcs);
    }
}
